### ISSUE TITLE
PCDM-session crashes when pressing Select Driver  button on the logon screen

### ISSUE THREAD

**Issue by maxsteciuk** [project-trident/trident-core#30]
**Describe the bug**
As soon as Trident booted to the logon screen and when the Select Driver button in the upper right corner was pressed the following crash of occurred PCDM-session process.
The core dump was generated and in general it indicates at the issue of deallocating memory source via free() hook to jemalloc 

**To Reproduce**
1. Boot Trident
2. Press Select Driver button in the upper right corner of the logon screen
3. Observe the crash and check core dump generated if core dump generation is enabled

**Expected behavior**
Daemon does not crash

**Screenshots**
N/A

**OS Version:**
Trident RC 1

**Additional context**
Please see core dump below
`Core was generated by `/usr/local/bin/PCDM-session -once vt9'.
Program terminated with signal SIGABRT, Aborted.
#0  thr_kill () at thr_kill.S:3
3       thr_kill.S: No such file or directory.
[Current thread is 1 (LWP 100492)]
(gdb) bt
#0  thr_kill () at thr_kill.S:3
#1  0x0000000801b00f04 in __raise (s=6) at /usr/src_tmp/lib/libc/gen/raise.c:54
#2  0x0000000801b00e79 in abort () at /usr/src_tmp/lib/libc/stdlib/abort.c:67
#3  0x0000000801ab26f6 in __je_rtree_leaf_elm_lookup_hard (tsdn=<optimized out>, rtree=<optimized out>, 
    rtree_ctx=0x80052a0b8, key=140737488349128, dependent=<optimized out>, init_missing=<optimized out>)
    at jemalloc_rtree.c:239
#4  0x0000000801afd696 in rtree_leaf_elm_lookup (rtree=0x6, init_missing=false, tsdn=<optimized out>, 
    rtree_ctx=<optimized out>, key=<optimized out>, dependent=<optimized out>)
    at /usr/src_tmp/contrib/jemalloc/include/jemalloc/internal/rtree.h:381
#5  rtree_read (tsdn=<optimized out>, rtree=<optimized out>, rtree_ctx=<optimized out>, key=<optimized out>, 
    dependent=<optimized out>) at /usr/src_tmp/contrib/jemalloc/include/jemalloc/internal/rtree.h:406
#6  0x0000000801af635a in rtree_szind_slab_read (dependent=255, tsdn=<optimized out>, rtree=<optimized out>, 
    rtree_ctx=<optimized out>, key=<optimized out>, r_szind=<optimized out>, r_slab=<optimized out>)
    at /usr/src_tmp/contrib/jemalloc/include/jemalloc/internal/rtree.h:458
#7  ifree (tsd=0x80052a090, ptr=0x7fffffffe7c8, tcache=0x80052a250, slow_path=true) at jemalloc_jemalloc.c:2210
#8  0x0000000801af6b82 in __free (ptr=0x7fffffffe7c8) at jemalloc_jemalloc.c:2404
#9  0x00000000004aa301 in ?? ()
#10 0x00000000004ab530 in ?? ()
#11 0x00000000004a8095 in ?? ()
#12 0x0000000800511000 in ?? ()
#13 0x0000000000000000 in ?? ()
`

**Comment by maxsteciuk** [comment]
Crash by segmentation fault was fixed and smoke tested , please see pull request: https://github.com/project-trident/pcdm/pull/14
